# EXTRACTION

video_dir: "../../"
frame_save_dir: "../../"
csv_path: "../../"

frame_rate       : 0.25  # seconds per frame (0.25 = 4fps)
target_max       : 400   # max frames to extract per part


# AUGMENTATION 

yolo_dir: "../../"
yolo_save_dir: "../../"

horizontal_flip:
  prod: 0.5

vertical_flip:
  prod: 0.5

rotate:
  prod: 0.5

blur:
  prod: 0.3

noise:
  prod: 0.3

mosaic:
  prod: 0.1

mixup:
  prod: 0.1
