# EXTRACTION

video_dir: "C:\\Users\\sawna\\Desktop\\HPPK_DP\\data\\raw"
frame_save_dir: "C:\\Users\\sawna\\Desktop\\HPPK_DP\\data\\processed" 
csv_path: "C:\\Users\\sawna\\Desktop\\HPPK_DP\\data\\raw\\pt.csv"

frame_rate       : 45  # seconds per frame (0.25 = 4fps)
target_max       : 400   # max frames to extract per part


# AUGMENTATION 

yolo_dir: "C:\\Users\\sawna\\Desktop\\error_test\\case"
yolo_save_dir: "C:\\Users\\sawna\\Desktop\\error_test\\pcs"

copy: true
multiplier: 2
mixup: false