# EXTRACTION

video_dir: "../../"
frame_save_dir: "../../"
csv_path: "../../"

frame_rate       : 0.25  # seconds per frame (0.25 = 4fps)
target_max       : 400   # max frames to extract per part


# AUGMENTATION 

yolo_dir: "../../"
yolo_save_dir: "../../"

horizontal_flip:
  apply: true

vertical_flip:
  apply: true

rotate:
  apply: true

noise: 
  apply: true

mosaic:
  apply: true

mixup:
  apply: true
