# MODE 

mode:            "" # strict or normal

# EXTRACTION

video_dir:       ""
frame_save_dir:  "" 
csv_path:        ""

frame_rate:      0  # seconds per frame (0.25 = 4fps)


# AUGMENTATION 

image_dir:       ""
image_save_dir:  ""

task:            "" # Detection or Classification
copy_mult:       0
aug_mult:        0
mixup_mult:      0
mosaic_mult:     0


